substitutions:
  name: natacha
  friendly_name: Natacha
esphome:
  name: natacha
#  friendly_name: Natacha
esp8266:
  board: d1_mini_pro
# Enable Home Assistant API
api:
  encryption:
    key: "XXXXXX"
ota:
  password: "XXXXXX"
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Natacha Fallback Hotspot"
    password: "XXXXXX"
captive_portal:
# Enable logging
logger:
  baud_rate: 0
  level: DEBUG #DEBUG NONE VERBOSE
  uart:
  id: uart_bus
#  tx_pin: TX
  rx_pin: 
    number: RX
    inverted: true
  baud_rate: 115200
  #data_bits: 7
  #parity: EVEN
  #stop_bits: 1
  rx_buffer_size: 1700  
dsmr:
#  request_pin: D5
#  request_interval: 10s
  id: dsmr_instance
  crc_check: false
  max_telegram_length: 1700
sensor:
  - platform: dsmr
    energy_delivered_tariff1:
      name: ${friendly_name} Energy Delivered Tariff 1
      state_class: total_increasing
    energy_returned_tariff1:
      name: ${friendly_name} Energy Returned Tariff 1
    power_delivered:
      name: ${friendly_name} Power Consumed
    power_returned:
      name: ${friendly_name} Power Returned
    electricity_failures:
      name: ${friendly_name} Electricity Failures
    electricity_long_failures:
      name: ${friendly_name} Electricity Long Failures
    voltage_l1:
      name: ${friendly_name} Voltage L1
    current_l1:
      name: ${friendly_name} Current L1
    power_delivered_l1:
      name: ${friendly_name} Power Delivered L1
    power_returned_l1:
      name: ${friendly_name} Power Returned L1
text_sensor:
  - platform: dsmr
    identification:
      name: ${friendly_name} Identification
#    p1_version:
#      name: ${friendly_name} Version
    # Belgium
    p1_version_be:
      name: ${friendly_name} Version BE
    electricity_tariff:
      name: "DSMR Tariff"    
    message_long:
      name: "DSMR Message Long"
      icon: mdi:message-text-outline    
  - platform: wifi_info
    ip_address:
      name: "smartmeter IP Address"
    ssid:
      name: "smartmeter Wi-Fi SSID"
    bssid:
      name: "smartmeter Wi-Fi BSSID"
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true
